# Site settings
title: Marc Streit
email: marc.streit@jku.at
description: "Marc Streit, Assistant Professor @ Johannes Kepler University Linz, Austria. His scientific ares of interest include information visualization, visual analytics, and biological data visualization."
baseurl: "/website-marc"
url: "http://marc-streit.com"
twitter: marc_streit
github:  mstreit
google_scholar: l7TTSP0AAAAJ
linkedin: 93766016
safe: false
lsi: false
plugins: ./_plugins
google_analytics: "'UA-28057314-1'"
use_analytics: true

paper_content_url: http://data.caleydo.org/papers/
poster_content_url: http://data.caleydo.org/posters/
caleydo_url: http://caleydo.org/

# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
sass:
  sass_dir: _sass

# exclude from build
exclude: ["README.md", "Rakefile", "changelog.md", ".idea/", "Gemfile", "Gemfile.lock", "rvm.env"]

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/
  persons:
    output: false
    permalink: /persons/:path/
  publications:
    output: true
    permalink: /publications/:path/
  thesis:
    output: true
    permalink: /thesis/:path/
  videos:
    output: true
    permalink: /videos/:path/